name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
        java-package: jdk

    - name: Build

      run: |
        mkdir target
        timestamp=$(date -u +%Y%m%d-%H%M%S)
        echo "TIMESTAMP=${timestamp}" >>$GITHUB_ENV
        bash prepareValidationArtefacts-github.sh target github ${timestamp}z DELETE-REPOSITORY-FILES-AS-WELL

    - uses: actions/upload-artifact@v3
      with:
        name: Validate-20022-github-${{ env.TIMESTAMP }}z
        path: ./*
